version: '3.8'
services:

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shahv12
      MYSQL_DATABASE: MovieProj
    ports:
      - "3307:3306"

  eureka:
    build: ./EurekaServer
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  movie-service:
    build: ./movie_service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/MovieProj
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=shahv12
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka

  review-service:
    build: ./review_service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/MovieProj
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=shahv12
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka

  recommendation-service:
    build: ./recommendation_service
    ports:
      - "8084:8084"
    depends_on:
      - movie-service
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/MovieProj
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=shahv12
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka

  api-gateway:
    build: ./api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - recommendation-service
      - movie-service
      - review-service
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka